spring:
  application:
    name: monitoring

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9a201.p.ssafy.io/almighty?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&charSet=utf8mb4
    username: ${USERNAME_MYSQL}
    password: ${PASSWORD_MYSQL}

  data:
    mongodb:
      username: ${USERNAME_MONGO}
      password: ${PASSWORD_MONGO}
      host: k9a201.p.ssafy.io
      port: 27017
      database: bms
    redis:
      repositories:
        enabled: false
  redis:
    host: www.batteryalmighty.co.kr
    password: almighty201
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


bms:
  url: http://localhost:8085

logging:
  level:
    com.example : DEBUG
jwt:
  secret: ${SECRET_KEY}
  refresh-token-validity-in-seconds: 1209600
  access-token-validity-in-seconds: 43200
openai:
  api:
    key: ${OPENAI_KEY}